"use strict";
import "./libs/dayjs.js";
import "./styles/global.css";
import "./styles/form.css";
import "./styles/schedule.css";
import "./models/form/submit.js";
import "./models/page-load.js";
import "./models/form/date-change.js";
import "./components/Modal.js";
